### ISSUE TITLE
Github - Node.js 16 actions are deprecated.

### ISSUE THREAD

**Issue by jkutes** [necojackarc/auto-request-review#116]
[Auto Request Review]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: necojackarc/auto-request-review@v0.12.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by necojackarc** [comment]
Thanks for pointing that out 👍 Resolved in #117
