### ISSUE TITLE
Hidden files not covered by ** glob

### ISSUE THREAD

**Issue by lmvco** [necojackarc/auto-request-review#65]
Using this example:
```
files:
  # Keys are glob expressions.
  # You can assign groups defined above as well as GitHub usernames.
  '**':
    - repository-owners # group
    - team:external-reviewers # GitHub team
```

if the PR only contain changes files inside a hidden folder (e.g. .github), the reviewers are not added.

Output:
```
No default reviewers are matched; terminating the process
```

**Comment by necojackarc** [comment]
@lmvco I played around with it but It looks like that's how `glob` works.

<img width="489" alt="image" src="https://user-images.githubusercontent.com/7670322/169578813-e978dba2-1165-46d5-ad3a-2af7f3e02b72.png">

I think you can use `{**,.**,.**/**}` or something similar to cover files and directories starting `.`.

<img width="535" alt="image" src="https://user-images.githubusercontent.com/7670322/169579366-c0a5aab0-fd73-48f3-b1b6-beecf6e2000b.png">

Ref: https://www.digitalocean.com/community/tools/glob

---

FYI - the glob logic is implemented with [minimatch](https://www.npmjs.com/package/minimatch)
